### ISSUE TITLE
Implement in memory index query filter processor

### ISSUE THREAD

**Issue by gdbrown** [gdbots/ncr-php#1]
When `Ncr::findNodeRefs` executes it may at some point need to evaluate an array of `IndexQueryFilter` objects against a set of `Node` objects and return only the nodes that match the filter.

The primary use case for this is the `InMemoryNcr` as it can then be used in unit tests that depends on index queries.

The secondary use case is to fill the gap where storage engines don't support filtering on secondary indices (what the IndexQuery is) or don't support it fully.  Like in the case of dynamodb,  you can only have one rule against the range key.

Create a class called `IndexQueryFilterProcessor` which will accept an array of nodes and an array of filters and return an array (always an array, even if empty) of nodes that matched.
> Note: for dynamodb implemented it to accept array of values.

make a branch off of 'beta' called 'index-query-filter-processor'.

**Comment by excelwebzone** [comment]
> Note: it's not supporting array operations

```php
    const EXISTS = 'exists';
    const IN = 'in';
    const CONTAINS = 'contains';
    const NOT_CONTAINS = 'not_contains';
```
